resolver: nightly-2022-02-07
extra-deps:
  - git: https://github.com/nikita-volkov/coalmine
    commit: 2d0693bf83aba1427d0973fe2ad7b9bc685781cf
  - git: https://github.com/nikita-volkov/fx
    commit: a612390cf54c37150c367324b154170921b98318
  - git: https://github.com/nikita-volkov/moore-machines
    commit: 7e95c33b203a1cfe42dbc0e0de3cec8e6fe94290
  - git: https://github.com/nikita-volkov/yaml-unscrambler
    commit: 630840e20698389f30a75d5af5c0b8ba249f5600
  - git: https://github.com/nikita-volkov/text-builder
    commit: 78b676ed8f042e28dfef92c882b3b47d7e2391da
  - aeson-2.0.3.0
  - aeson-value-parser-0.19.6
  - yaml-0.11.7.0
  - vector-extras-0.2.6
