

component Package
component Code
component Exp
component Type
component Declaration
component Module
component GroupingCode

Package --> Module : Composes
Module --> Code : Composes
Declaration --> Code : Extends
GroupingCode --> Code : Extends
Exp --> GroupingCode : Extends
Type --> GroupingCode : Extends
