

component Package
component Code
component Exp
component Type
component Declaration
component Module

Package --> Module : Composes
Code --> Module : Compiles into
Code --> Exp : Composes
Code --> Type : Composes
Code --> Declaration : Composes
Declaration --> Exp : Composes
Declaration --> Type : Composes
