

component Package
component Code
component Exp
component Type
component Declaration
component Module

Package --> Module : Composes
Module --> Code : Composes
Exp --> Code : Compiles into
Type --> Code : Compiles into
Declaration --> Code : Compiles into
Code --> Exp : Composes
Code --> Type : Composes
Code --> Declaration : Composes
